CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "created_at" datetime DEFAULT (now())
);

CREATE TABLE "occasions" (
  "occasion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "occasion_type" varchar NOT NULL,
  "message_content" text NOT NULL,
  "delivery_method" varchar NOT NULL,
  "date_time" datetime NOT NULL,
  "created_at" datetime DEFAULT (now())
);

CREATE TABLE "delivery_history" (
  "delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "occasion_id" int NOT NULL,
  "status" varchar NOT NULL,
  "timestamp" datetime NOT NULL
);

CREATE TABLE "user_audit_trail" (
  "audit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "action" varchar NOT NULL,
  "timestamp" datetime NOT NULL
);

CREATE TABLE "occasion_audit_trail" (
  "audit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "occasion_id" int NOT NULL,
  "action" varchar NOT NULL,
  "timestamp" datetime NOT NULL
);

ALTER TABLE "occasions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "delivery_history" ADD FOREIGN KEY ("occasion_id") REFERENCES "occasions" ("occasion_id");

ALTER TABLE "user_audit_trail" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "occasion_audit_trail" ADD FOREIGN KEY ("occasion_id") REFERENCES "occasions" ("occasion_id");
