"""empty message

Revision ID: 457ce474c7cf
Revises: cdb291e84f04
Create Date: 2024-02-08 21:37:13.280462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457ce474c7cf'
down_revision = 'cdb291e84f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.alter_column('receiver_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('receiver_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.alter_column('receiver_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('receiver_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
