"""Add is_repeated column to occasions table

Revision ID: 6eeb4007509d
Revises: 9911a4982e16
Create Date: 2024-02-04 08:09:24.828308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eeb4007509d'
down_revision = '9911a4982e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_repeated', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.drop_column('is_repeated')

    # ### end Alembic commands ###
