"""empty message

Revision ID: cdb291e84f04
Revises: a3b05f4a5441
Create Date: 2024-02-08 20:51:49.873970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb291e84f04'
down_revision = 'a3b05f4a5441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('receiver_phone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.drop_column('receiver_phone')
        batch_op.drop_column('receiver_email')

    # ### end Alembic commands ###
